### PR TITLE
Greetings in 10 African languages from api

### PR DESCRIPTION
**Pull request by Haywayaheadshot**
# What?

- A static UI that displays "Hello World!" in 10 African languages at random.

# Why?
 
- To practice how to make an app that takes rails database as its backend and react as its frontend.

# How?
- Created a new Rails app called 'hello-world-rails-react'.
- Used the command rails new -j webpack my_new_rails_app as described in the previous lesson's tutorial.
- Verified that the jsbundling-rails gem is added to your Gemfile.
- Initialized my project with Git.
- Installed needed node dependencies as described in the previous lesson's tutorial.
- Created a babel.config.js in the root folder of your project as described in the previous lesson's tutorial.
- Updated webpack.config.js to include the babel loader as described in the previous lesson's tutorial.
- Made sure that your project has a Postgres database set up.
- Created a table for storing your messages and create 5 different greetings.
- Created an API endpoint that selects a random greeting from your table.
- Created a static view that will be the root of your app.
- Created the App component with react-router and render it in your static view.
- Created the Greeting component that will display a greeting. Set it up as a route in your App component.
- Created a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Displayed the random greeting in my Greeting component.

### CODE REVIEW

**Review by t-yanick — COMMENTED** [review]
Hi @Haywayaheadshot , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a personalized ReadMe. Kindly add all the sections of the Microverse [ReadMe Template](https://github.com/microverseinc/readme-template) and personalize them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Haywayaheadshot** [comment]
@t-yanick Thank you for reviewing my project. Working on it asap

**Review by brytebee — APPROVED** [review]
Hi, @Haywayaheadshot👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 



Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
@brytebee Thank you for reviewing my project. Have a nice day

**Pull request merged**
